### ISSUE TITLE
CreditTerms should be creditTermsId on SupplierInvoice

### ISSUE THREAD

**Issue by martinberglund** [ON-IT/Visma.Net#100]
Hi

The class creditTerms on supplierInvoice should be like it is in dev branch on CustomerInvoice. So the name should be "creditTermsId".

public CreditTerms creditTerms
        {
            get { return Get<CreditTerms>("creditTermsId"); }
            set { Set(value, "creditTermsId"); }
        }

**Comment by omelhus** [comment]
Thanks. Fixed this in dev now.

**Comment by martinberglund** [comment]
Thanks, that was fast :)
