### ISSUE TITLE
Problem updating empty fields to empty value

### ISSUE THREAD

**Issue by angoyd** [ON-IT/Visma.Net#102]
Hi,

I have a problem with updating say an address line with empty value since CreateDto in the DtoProviderBase.cs compares string to check if string is null or empty.

```
   if (string.IsNullOrEmpty(string.Format("{0}", value)))
     return null;
```

I would like to change it to just check if its null but can't really grasp what it might affect, do you have any suggestions @omelhus ?

/Anders

**Comment by omelhus** [comment]
I cant think of any issues with changing this to a null-check, so just go ahead.

**Comment by omelhus** [comment]
Maybe check for default(T)?

**Comment by angoyd** [comment]
Yes that might be a good idea :)
