### ISSUE TITLE
Get customer note

### ISSUE THREAD

**Issue by sierdweidema** [ON-IT/Visma.Net#108]
I would like to get the note from a specific customer using the following Get url:
https://integration.visma.net/API/controller/api/v1/customer/{customerCd}/note

I assume the CustomerData class should be extended with the following method:

```
public async Task<string> GetNoteFor(string customerNumber)
        {
            return
                await
                    VismaNetApiHelper.Get<string>($"{customerNumber}/note", VismaNetControllers.Customers, Authorization);
        }
```

**Comment by omelhus** [comment]
Hey!

If you use the pre-release on nuget you can do the following to get the note. All endpoints will be available using dynamic.

```
dynamic note = await vismaNet.Dynamic.Customer["10003"].Note.Get();
```

**Comment by sierdweidema** [comment]
Hi Ole, That is great, will give it a try. Thanks!
