### ISSUE TITLE
Streams from dynamic endpoints

### ISSUE THREAD

**Issue by Hironiem** [ON-IT/Visma.Net#119]
Is there a way to get streams through the dynamic endpoints, such as print customer credit note?

It seems that now it's only possible to use Get() on the dynamic, which casts it as JObject.
`return await VismaNetApiHelper.Get<JObject>(argument, $"{_base}{_endpointName}", _auth);`

I'm getting the print with
`await vismaClient.Dynamic.CustomerCreditNote["100001"].Print.Get();`

**Comment by omelhus** [comment]
How about adding .GetStream() to access the underlying stream?
