### ISSUE TITLE
[Question] Recurring invoices

### ISSUE THREAD

**Issue by hakimio** [ON-IT/Visma.Net#125]
Hi,

Do you know if "Visma Financials" supports recurring invoices like [Visma eAccounting does](https://help.visma.net/nl_en/eaccounting/content/online-help/b-sales-create-recurring-invoice.htm)?

**Comment by reositter** [comment]
Hi, Yes VN supports recurring transactions. Both for customer, supplier and accounting. For customer invoices, go to screeen ScreenId=AR203500

**Comment by hakimio** [comment]
Thank you :)

**Comment by hakimio** [comment]
@reositter Do you also know how to create "Recurring Transactions" using Visma API?

**Comment by reositter** [comment]
Hi, I took a quick look at the api definition, and can't see that thats possible to do through the API.

**Comment by hakimio** [comment]
I see. Thanks for taking a look at it.
