### ISSUE TITLE
Plans for Paging changes

### ISSUE THREAD

**Issue by Hironiem** [ON-IT/Visma.Net#129]
Is there a planned release for the paging changes in dev? 

Seems the new rules for using paging will be enforced starting May 12th.

And there are a couple endpoint missing (CustomerSalesPrice for instance), is that something I could help out and fix?

**Comment by omelhus** [comment]
Hey!

The new pagination scheme is implemented in the dev branch, and it was activated for both salesorder and customerinvoice when it actually was broken in those endpoints.

I've just pushed a change to the dev branch enabling this again, so the change should be visible and available on nuget within the hour.

If you have the capacity to add CustomerSalesPrice or other endpoint your contribution is most welcome!
