### ISSUE TITLE
SalesOrder/CreateShipment

### ISSUE THREAD

**Issue by col-papaavola** [ON-IT/Visma.Net#135]
Hello All,
Thanks for easy to use library.

I found problem from SalesOrder/CreateShipment method.
Visma.net library saves returning values to `VismaActionResults` class.
Visma returns `CreateShipmentActionResultDto` that contains same info than `VismaActionResults` but also `ShipmentDto`
`ShipmentDto` contains created shipment number, that is important for my code.

I was fix this in my code by adding row `public ONIT.VismaNetApi.Models.Shipment ShipmentDto { get; set; }` to VismaActionResults class in Visma.Net.

Another way is create new class CreateShipmentActionResultDto and make needed changes to code in Visma.net. (This is breaking change for people who are already using this method) 

I'm not master of coding arts, so I ask whitch one is accepted method if I make pull request for fixing this?

Edit: Also `ReferenceNumber` is missing from VismaActionResults.

**Comment by omelhus** [comment]
Hey,

Thanks for that and thanks for wanting to contribute!

Create a class that inherits from VismaActionResult. This will ensure backwards compatibility, and still provide the necessary information.

```csharp
public class ShipmentVismaActionResult : VismaActionResult {
 [JsonProperty]
 public string referenceNumber { get; internal set; }
 [JsonProperty("shipmentDto")]
 public ShipmentDto shipment { get; internal set; }
}
```

**Comment by col-papaavola** [comment]
Here you go.
I make pull request
