### ISSUE TITLE
SupplierInvoice Returns duplicate objects

### ISSUE THREAD

**Issue by Snuffsis** [ON-IT/Visma.Net#143]
Using the SupplierInvoice.GetAllModifiedSince function returns the correct amount of supplierinvoices, but a large amount of these are duplicates of each other.

Not sure if the calling is incorrect, or if its an issue with the method in the library?

Using RestClient and writing my own loop (or testing with Postman) returns one of each as it should. 

Code snippet:

```
public async Task CreateOrUpdate()
{
    var dateTime = DateTime.Now.AddMonths(-2);
    var vismaNet = new VismaNet(company-id, "token");
    var vSupplierInvoices = await vismaNet.SupplierInvoice.GetAllModifiedSince(dateTime);

...more code for using the result...
}
```

**Comment by omelhus** [comment]
Hey,

What version of the library are you using? Latest dev?

**Comment by Snuffsis** [comment]
Not using Dev, I am using the latest version 3.7.1

**Comment by omelhus** [comment]
Ok, thanks. I've found a bug that will cause this and I will update shortly.

**Comment by omelhus** [comment]
You can try the package Visma.net 3.7.2-pre-68 to see if the issue is still present.

**Comment by Snuffsis** [comment]
Updated and tried with the new 3.7.2.1 version and the issue seems to be fixed. No supplierinvoices are being duplicated.

**Comment by omelhus** [comment]
Thank you!
