### ISSUE TITLE
Add pagination to segment Endpoints

### ISSUE THREAD

**Issue by tadrian** [ON-IT/Visma.Net#145]
Currently the segment endpoints do not support pagination. 

This method works with pagination to get all invoices for all customers

VismaNet.CustomerInvoice.All();
https://integration.visma.net/API/controller/api/v1/customerinvoice?pageSize=5&pageNumber=1
https://integration.visma.net/API/controller/api/v1/customerinvoice?pageSize=5&pageNumber=2
etc

This method gets all the invoices if less than limit 500
VismaNet.CustomerInvoice.ForCustomer("10003");

url should be:
https://integration.visma.net/API/controller/api/v1/customer/10003/invoice?pageSize=5&pageNumber=1
https://integration.visma.net/API/controller/api/v1/customer/10003/invoice?pageSize=5&pageNumber=2
etc

ForCustomer method
https://github.com/ON-IT/Visma.Net/blob/master/Visma.net/lib/DAta/CustomerInvoiceData.cs

FetchInvoicesForCustomerCd method
https://github.com/ON-IT/Visma.Net/blob/master/Visma.net/lib/VismaNetApiHelper.cs

**Comment by omelhus** [comment]
Fixed in #179, release [4.0.0](https://github.com/ON-IT/Visma.Net/releases/tag/v4.0.0)
