### ISSUE TITLE
SupplierInvoice.Add throws exception when type is DebitAdj

### ISSUE THREAD

**Issue by Snuffsis** [ON-IT/Visma.Net#147]
This is probably because of Visma.NETs API not being able to return SupplierInvoices from the same endpoint. And the fact that this package asks for the created supplierinvoice.

But the SDK will throw an exception that it did not find the specified supplierinvoice, even though it exists, because it is of type DebitAdj (Kreditfaktura), even though the supplierinvoice has in fact been created.

Is it possible to add support for returning the created supplier invoices ID alongside the exception perhaps?

EDIT: Or perhaps, have the returnvalue call for the endpoint that has the documenttype parameter with it, so it can return it.

**Comment by omelhus** [comment]
Hey! Can you provide me with a couple of sample calls so that I can recreate the issue?

**Comment by Snuffsis** [comment]
Sure,

This is what I used when this occured.

```
var supplierInvoice = new SupplierInvoice()
{
	documentType = SupplierDocumentType.DebitAdj,
	description = invoice.Order,
	supplier = new SupplierNumber() { number = "50000" },
	balanceInCurrency = Math.Abs(invoice.OrderTotal),
	supplierReference = invoice.Order
};
var invoiceLines = new List<SupplierInvoiceLine>();

var subaccount = new ONIT.VismaNetApi.Models.CustomDto.Subaccount();

subaccount.segments.Add(new Segment()
{
		segmentId = 1,
		segmentValue = "000000"
});

subaccount.segments.Add(new Segment()
{
	segmentId = 2,
	segmentValue = "00"
});

invoiceLines.Add(new SupplierInvoiceLine()
{
	quantity = 1,
	costInCurrency = Math.Abs(OrderTotal),
	unitCostInCurrency = Math.Abs(OrderTotal),
	subaccount = subaccount,
	transactionDescription = "Fakturaunderlag " + Order
});

foreach (var invoiceLine in invoiceLines)
{
	supplierInvoice.Add(invoiceLine);
}

SupplierInvoice createdSupplierInvoice = null;
string errorMessage = "";
try
{
	createdSupplierInvoice = await newVismaNet.SupplierInvoice.Add(supplierInvoice);
}
catch (VismaNetException ex)
{
    Console.WriteLine(ex.Message);
}
```

**Comment by Snuffsis** [comment]
Might also add that, even with my work around (parsing the error message to get the invoice number) for adding an attachment, it will fail again, as it requires the "documentType" section of the URI to add attachments to DebitAdj types.

**Comment by omelhus** [comment]
Thank you! Can you test with the latest preview package?

**Comment by Snuffsis** [comment]
Just tested it with the latest preview package.
Worked as expected with the creation of the supplierinvoice now. Still throws the same exception when trying to create attachments however.

**Comment by omelhus** [comment]
Did you try specifying the document type for the attachment?

**Comment by Snuffsis** [comment]
The function "AddAttachmentToInvoice" does not take a parameter for documenttype. It only takes invoicenumber, conten (stream, byte[] or string) and the filename.

**Comment by omelhus** [comment]
I guess it'll help if I push the changes.

**Comment by Snuffsis** [comment]
Yes, excellent, that did in fact help.

It now works as expected.
