### ISSUE TITLE
Better handling of 404 exceptions

### ISSUE THREAD

**Issue by johandse** [ON-IT/Visma.Net#149]
I would like to implement handling of 404 exceptions for get methods (I want to see the difference between an invalid document number and other problems). Would such pull request be accepted (it will be a breaking change)? I think the best way would be to add a new exception type (DocumentNotFoundException).

**Comment by omelhus** [comment]
How about adding it with an option to enable it? 

We could add an optional config class to the ctor of VismaNet and enable it from there?

**Comment by johandse** [comment]
Sounds like a good idea. Unfortunately I don´t think I am the right person to do that in a good way. For the moment I changed my application to manually handle the rare case that a document have been deleted in Visma.Net, so this functionality is not needed now.
