### ISSUE TITLE
Add new location gives error about missing BAccountId 

### ISSUE THREAD

**Issue by eriksallberg** [ON-IT/Visma.Net#150]
I tried with both: 
Location location = new Location(customer.number, "new-id");
and
location.baccount = new Baccount() { number = customer.number, name = customer.name, internalId = customer.internalId };

Both gives the same error.

Adding a location works in version 3.6.0, so I've reverted back to that version for now.

**Comment by omelhus** [comment]
@angoyd any thoughts on this one?

Looks like there was a change in Visma.net/Models/Location.cs that changes handing of baccounts.

What if you try
```charp
var location = new Location(customer.number, "new-id", true);
```

**Comment by angoyd** [comment]
I have used it like this
`location = new ONIT.VismaNetApi.Models.Location(InvoiceCustomer.number.Trim(), "New-location-id", true);`
I havn´t got any indication about that it shouldn't been working.

**Comment by angoyd** [comment]
Can´t remember, but I know I had problems with it... but not exactly what it was.... Suppose it gives the same result in the json it would work...
