### ISSUE TITLE
attachments for CustomerCreditNote endpoint

### ISSUE THREAD

**Issue by Snuffsis** [ON-IT/Visma.Net#182]
When trying to add an attachment to a created customercreditnote, it returns that it can't find the document that was previously created.

Looking through the code. I can see that the Data object for customerCreditNote sets the endpoint correctly, as seen here:
![image](https://user-images.githubusercontent.com/8822958/166485459-01145b86-a2ca-4725-94bf-ef87b303346b.png)

However, when you then call upon the method for adding an attachment, it goes to the VismaNetApiHelpers addattachmenttocreditnote which resets the url to just "creditnote" instead.

![image](https://user-images.githubusercontent.com/8822958/166485343-2082a9b6-5f46-4e4b-9369-f0be587179cc.png)

Would it be possible to get a fix for this where it has its own helper method for customercreditnote so this possible does not happen?

**Comment by omelhus** [comment]
Hey!

Thanks for the thorough issue report. I'll see if I can get a fix out for this tomorrow. 

Cheers!

**Comment by MichelV96** [comment]
Hi,

Fix has already ben made and is in the latest DEV prerelease
https://github.com/ON-IT/Visma.Net/pull/181
