### ISSUE TITLE
Create CustomerInvoice and SupplierInvoice with own number (auto numbering disabled)

### ISSUE THREAD

**Issue by sierdweidema** [ON-IT/Visma.Net#34]
I would like to create customer and supplier invoices with auto numbering disabled, so with referenceNumber set in the object.

**Comment by omelhus** [comment]
CustomerInvoice already had this implemented. Let me know if something doesn't work out.

Also, please set VismaNet.ApplicationName as described on the front page, so that Visma knows who's who.

**Comment by sierdweidema** [comment]
Hi Ole,

Thanks again!

Kind regards,

Sierd Weidema
Consultant / Ontwikkelaar

Arch-IT BV

[cid:image001.jpg@01D06AF7.C4673970]

Winnaar Klanttevredenheid Award 2014!
Klanten van Arch-IT blijken de meest tevreden en trouwe AccountView- en Visma.net gebruikers te zijn!



Van: Ole Melhus [mailto:notifications@github.com]
Verzonden: dinsdag 6 december 2016 14:29
Aan: ON-IT/Visma.Net <Visma.Net@noreply.github.com>
CC: Sierd Weidema <Sierd.Weidema@arch-it.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [ON-IT/Visma.Net] Create CustomerInvoice and SupplierInvoice with own number (auto numbering disabled) (#34)


CustomerInvoice already had this implemented. Let me know if something doesn't work out.

Also, please set VismaNet.ApplicationName as described on the front page, so that Visma knows who's who.
