### ISSUE TITLE
Creating Supplier without autonumbering enabled fails

### ISSUE THREAD

**Issue by sierdweidema** [ON-IT/Visma.Net#43]
When creating a Supplier with autonumbering disabled, the request fails with the following message: 

_VismaId: d26ecd9e-7808-4ddd-bb1e-15a0bdf7f43b. Error inserting the supplier. Value cannot be null.
Parameter name: key_

Below two lines, with and without setting the constructor:
Supplier _supplier = new Supplier("12345") {name = "Test"}; --> fails
Supplier _supplier = new Supplier() {name = "Test"}; --> success

**Comment by omelhus** [comment]
This is an issue with the API. I've notified Visma, and will update when I hear back.
