### ISSUE TITLE
Get available contexts for user (token)

### ISSUE THREAD

**Issue by sierdweidema** [ON-IT/Visma.Net#49]
I would like to get the contexts for my token using the **'/security/api/v1/token/usercontexts'** endpoint. Therefore, there should be an VismaNet contructor with only one parameter 'token', I assume.

**Comment by omelhus** [comment]
Have a look at https://github.com/ON-IT/Visma.Net/wiki/Step-1%3A-Create-connection

**Comment by sierdweidema** [comment]
Thanks
