### ISSUE TITLE
Add segment values to segment

### ISSUE THREAD

**Issue by sierdweidema** [ON-IT/Visma.Net#52]
As mentioned in this post https://www.visma.com/software/support/portal/forum/showthread.php?9365-Create-segment-values-for-segment-SUBACCOUNT&p=17308#post17308 I would like to add segment values. 

I seem to miss the "operation" property which needs to be set:
```json
{
   "DimensionId":"Test",
   "SegementId":"1",
   "SegmentValues":[
      {
         "Operation":"Insert",
         "Value":"1",
         "Description":{
            "Value":"Testing-Create"
         },
         "Active":{
            "Value":true
         }
      }
   ]
}`

**Comment by omelhus** [comment]
This was implemented in [this commit](https://github.com/ON-IT/Visma.Net/commit/93b5628f3d13a6ef033196f71e2288fd63c6b0da), but it does not work in Visma.net yet. It will probably be released on 11/03/2017.
