### ISSUE TITLE
Use Dynamic instead of strongly typed

### ISSUE THREAD

**Issue by fredrikjacobson** [ON-IT/Visma.Net#60]
Is it possible to use the dynamic object instead of strongly typed for exsiting endpoints.
I'm trying to reach crossReference from the Inventory endpoint, which is not included in the Inventory Model and hence not in the result. 

To fetch this information I thought i could used the dynamic method but it seems to override to the strongly typed. Is there a workaround or do I have to include the repo as a solution and modify the models?

Thanks in advance.

**Comment by omelhus** [comment]
Hey,

Feel free to clone the repo, add the missing fields and send me a pull request. If not I can add the field next week.

- Ole

**Comment by omelhus** [comment]
I've now added crossReference to Inventory.
