### ISSUE TITLE
Create SalesOrder get endpoint

### ISSUE THREAD

**Issue by johnepedersen** [ON-IT/Visma.Net#71]
Suspect this is a Visma issue, but I post here also. when I create a salesorder with ordertype IN the result.header.location.absoluteuri goes to https://integration.visma.net/API/controller/api/v1/salesorder/{orderno} which gives me a 404, when i hack the url to https://integration.visma.net/API/controller/api/v1/salesorder/IN/000380 it works. 

these salesorders (invoice) have been working before, so not sure what have changed, maybe Visma return a different header than before?!

for my purpose it is sufficient to add 
 url = url.Replace("salesorder/", "salesorder/IN/");
in VismaNetWebClient.cs line 145

John Even Pedersen

**Comment by omelhus** [comment]
This looks definitely like a Visma.net issue. Please report it in the forums. 

I don't feel like we should create a workaround for this.

**Comment by angoyd** [comment]
@omelhus  I think this is the way they are handling diffrent ordertypes now.

**Comment by omelhus** [comment]
Yes, but the location header should be the correct URL to the sales order. I think they've forgotten something.

**Comment by angoyd** [comment]
Yes, of course didnt read the first message throw...

But we have an issue when putting an salesorder, the get after the put is for the url that we have put to but it should be with the orderType in between since we an´t getting any Url in retrurn.

Cut from VismaNetWebClient.cs line 234

> if (result.Headers.Location != null)
>   return await Get<T>(result.Headers.Location.AbsoluteUri);
> if (result.StatusCode == HttpStatusCode.NoContent)
>  return await Get<T>(url);

Any suggestion for a generic fix for that?

**Comment by johnepedersen** [comment]
I created a ticket with Visma, but it didnt seem to get recognized. 
https://www.visma.com/software/support/portal/forum/showthread.php?10751

But for my purposes right now the replace is sufficient.

**Comment by omelhus** [comment]
I don't think they understand the issue.

@angoyd: have you tested this solution? Because I think the issue is that the returned location header is invalid, and thus your fix will never be reached. I haven't investigated any further yet.

**Comment by omelhus** [comment]
@angoyd I'm seeing your solution will work for updates but not create.

**Comment by angoyd** [comment]
@omelhus the create case I think is a Visma API problem but the updates do not return any headers nor content and then we have to take care of this at our side and then tell Visma to fix the create return error or what do you think?

**Comment by omelhus** [comment]
Yes, it actually seems like we're going to have to create a workaround for this our selves. I'll give it a go.

**Comment by angoyd** [comment]
@omelhus I actually had to fix it since one of our customer is stuck.... So I have a solution soon ready, have you had time to look at my other pull request?

**Comment by omelhus** [comment]
Ok. Create a new pull request if you'd like when you're done.

I cannot merge your other pull request as it is 16 changed files and targeting master. I'll have to merge it manually in a separate branch to get them in. I've replied in the pull request as well.

**Comment by angoyd** [comment]
You have mig suggestion [here](https://github.com/angoyd/Visma.Net/commit/7b14cf3037f09fd57a3e6e8e9d46a135f28279eb)

What branch do you want me to target in the future?

**Comment by omelhus** [comment]
Please target dev

**Comment by johnepedersen** [comment]
I see Visma moved it to Reported Bugs, thanks for weighing in

**Comment by angoyd** [comment]
@johnepedersen the dev branch now handles the error in the links for create and update

**Comment by omelhus** [comment]
Visma.net 3.0.0 is finally released on NuGet. This version includes @angoyds changes. Good work!
