### ISSUE TITLE
Getting code using OAuth

### ISSUE THREAD

**Issue by gronhovd** [ON-IT/Visma.Net#74]
Hi,
Are there any good solution, without implementing a webserver which respond to callback, to fetch 'code', which is part of the callback-url? This 'code' is dynamic and is essential for getting the token (using the api-method VismaNet.GetTokenUsingOAuth(dev_client_id, dev_secret, code, redirect_url);

**Comment by omelhus** [comment]
No, with the exception of including a web browser in a WPF/WinForms-application and watch the urls, there's not. If you just want a webserver for the purpose of fetching the token I'd suggest that you have a look at including Katana/OWIN self-hosted in your console application.

See https://docs.microsoft.com/en-us/aspnet/aspnet/overview/owin-and-katana/getting-started-with-owin-and-katana#self-host-owin-in-a-console-application for details on how to implement it.
