### ISSUE TITLE
Building Visma.Net project

### ISSUE THREAD

**Issue by lafar6502** [ON-IT/Visma.Net#75]
Question: how to build this project using standard .net framework, not the .Net core version?
Is it possible to do the build in Visual Studio 2015? Or how to convert it to vs project in a recommended way?
Thanks
RG

**Comment by omelhus** [comment]
Using Visual Studio 2017 the project builds for both .Net Core and .Net Framework 4.6.1. If you don't have access to Visual Studio 2017 I'd suggest that you pull in the nuget package. Is using .Net Framework 4.6.1 an issue for you?
