### ISSUE TITLE
Error when creating customer with customized number (Customer ID)

### ISSUE THREAD

**Issue by gronhovd** [ON-IT/Visma.Net#78]
Hi,
I've configured Visma.net to allow creating customers with customized CustomerID, that means that autonumbering for CustomerID is turned off. (The customerID is based on another system - and has to be equal for mapping-reasons)

When I try to create a new customer, after I've made changes in this configuration, the method for creating new customer throws an error that saying 'Customer ID cannot be empty'.

This code:
var newCustomer = new Customer {name = "Pål Birkeland", number = "12345678"};
var createdCustomer = await vismaNet.Customer.Add(newCustomer);

throws this error:
InnerException	{"VismaId: 30f6cee2-b3fa-4413-a084-2d18f9333e9c. Error inserting the customer. Error: Inserting 'Customer' record raised at least one error. Please review the errors.\r\nError: 'Customer ID' cannot be empty.\r\n"}	System.Exception {ONIT.VismaNetApi.Exceptions.VismaNetException}

Regards,
Per Rune Grønhovd

**Comment by omelhus** [comment]
Hi,

If you've turned auto customerid off, you'll have to use a different constructor.

```csharp
var newCustomer = new Customer("12345678") {name = "Pål Birkeland"};
var createdCustomer = await vismaNet.Customer.Add(newCustomer);
```

This will send the customer number to Visma.net as well.
