### ISSUE TITLE
unable to load project convert it to MSbuild 2003 format  

### ISSUE THREAD

**Issue by robela** [ON-IT/Visma.Net#79]
I download code, I try to open code the project says load failed 
![error](https://user-images.githubusercontent.com/6640169/33425684-7ea80152-d5d0-11e7-80a0-6e09c3add2d3.png)

**Comment by omelhus** [comment]
Can you please elaborate on your problem? What are you trying to achieve?

**Comment by omelhus** [comment]
I'm closing this.

Please use Visual Studio 2017 if you want to make changes or contribute to the code. If you cannot use Visual Studio 2017 you'll have to use the [NuGet](https://www.nuget.org/packages/Visma.net) package.
