### ISSUE TITLE
Can't insert sales order after adding location

### ISSUE THREAD

**Issue by magnificentynwa** [ON-IT/Visma.Net#89]
When I add a location object to paramter location on the SalesOrder object I get the following error message. Tried several customers and locations with the same error every time.

ONIT.VismaNetApi.Exceptions.VismaNetException:` VismaId: 94e79109-2abd-4a4a-97ff-743e33812334. Error creating salesOrder. Visma.net.ERP.Web.Api.ExceptionHandling.PostException: Data received not recognized as SaleOrderUpdateDto ---> System.ArgumentNullException: Value cannot be null.  Parameter name: saleOrderUpdateDto     --- End of inner exception stack trace ---     at Visma.net.ERP.Web.Api.Controllers.V1.SalesOrderController.Post(SalesOrderUpdateDto saleOrderUpdateDto) in C:\BuildAgent\work\ed059f6a66b05143\Web\Lib\Visma.net.ERP.Web.Api\Controllers\V1\SalesOrderController.cs:line 150  Value cannot be null.  Parameter name: saleOrderUpdateDto     vid ONIT.VismaNetApi.VismaNetExceptionHandler.ThrowException(String data, Exception ex, String request, String endpoint)     vid ONIT.VismaNetApi.VismaNetExceptionHandler.HandleException(String data, Exception e, String request, String endpoint)     vid ONIT.VismaNetApi.Lib.VismaNetHttpClient.

**Comment by omelhus** [comment]
Hi,

I'm sorry I haven't responded to you yet on this matter. 

The issue was that the wrong class was set as the location on a sales order, and I've now changed this to LocationSummary instead.

This is in place in the pre-release and will be a part of the release that will be out today (22/05/2018).
