### ISSUE TITLE
County error updating location

### ISSUE THREAD

**Issue by eriksallberg** [ON-IT/Visma.Net#99]
I sometimes get the error down below when I try to update a location. Some locations I can update without any problem and some won't work. I even copied the info from one location that don't work to one that do work and it still works, so it seems not to be based on the location info.

Sorry I can't give you better info about what's wrong, I've been testing different scenarios for the last 90 minutes and can't find any patterns. 

ONIT.VismaNetApi.Exceptions.VismaNetException: VismaId: 7ddc7b01-c9cd-4692-b4f4-102e83bb76e9. Error: An error occurred during processing of the field County: Object reference not set to an instance of an object..     vid ONIT.VismaNetApi.VismaNetExceptionHandler.ThrowException(String data, Exception ex, String request, String endpoint)     vid ONIT.VismaNetApi.VismaNetExceptionHandler.HandleException(String data, Exception e, String request, String endpoint)     vid ONIT.VismaNetApi.Lib.VismaNetHttpClient.<Put>d__11`1.MoveNext()  --- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---     vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     vid ONIT.VismaNetApi.Lib.VismaNetApiHelper.<Update>d__34`1.MoveNext()  --- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---     vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     vid ONIT.VismaNetApi.Lib.Data.LocationData.<Update>d__2.MoveNext()  --- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---     vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     vid System.Runtime.CompilerServices.TaskAwaiter.GetResult()     vid WebbEdit.Bll.Visma.VismaService.<UpdateLocation>d__59.MoveNext() i 1658  --- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---     vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)     vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)     vid System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by omelhus** [comment]
It seems like the error arises from Visma.net. You should try posting this to the forum if you haven't already.

**Comment by omelhus** [comment]
You can try sending it without county though and see if that helps. County should be inferred by postal code anyways.
